name: riftinversion
channels:
  - davasey
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - geoscripts
  - pandas
  - jupyter
  - numpy
  - tqdm
  - matplotlib
  - pyvista
  - scipy
  - joblib
  - opencv
  - cmcrameri
